version: '{build}'
clone_depth: 25

branches:
  only:
    - master
    - devel
    - appveyor
    - /devel.*/
    - /.*-avy/
    - /ci-.*/

environment:
  GRAPHVIZ_VERSION: 2.38
  GRAPHVIZ_INSTALLER: graphviz-%GRAPHVIZ_VERSION%.msi
  PATH: '%APPDATA%\Python\%PYTHON%\Scripts;C:\%PYTHON%%ARCH%\Scripts;C:\%PYTHON%\Scripts;C:\Program Files (x86)\Graphviz%GRAPHVIZ_VERSION%\bin;%PATH%'
  matrix:
  - PYTHON: Python36
    EXTRA_ARGS: -m llvm
#  - PYTHON: Python37
#    EXTRA_ARGS: -m llvm
#  - PYTHON: Python38
#    EXTRA_ARGS: -m llvm

install:
  - if not exist %GRAPHVIZ_INSTALLER% appveyor-retry curl https://graphviz.gitlab.io/_pages/Download/windows/%GRAPHVIZ_INSTALLER% -o %GRAPHVIZ_INSTALLER%
  - msiexec.exe /i %GRAPHVIZ_INSTALLER% /passive
  - pip --version
  - pip install --user git+https://github.com/benureau/leabra.git@master

  # pytorch does not distribute windows packages over pypi. Install it directly.
  - if not "%ARCH%" == "" (pip install --user torch -f https://download.pytorch.org/whl/cpu/torch_stable.html)

  - pip install --user -e .[dev]

cache:
    - '%LOCALAPPDATA%\pip\Cache'
    - '%GRAPHVIZ_INSTALLER%'

build: off

test_script:
  - pytest --junit-xml=tests_out.xml -n auto --strict-markers %EXTRA_ARGS%

on_finish:
  # Upload tests to appveyor overview
  - appveyor-retry curl -X POST -F "file=@tests_out.xml" https://ci.appveyor.com/api/testresults/junit/%APPVEYOR_JOB_ID%
